spring:
  data:
    mongodb:
      database: "orderServiceDB"
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
  cache:
      type: redis
      redis:
        cache-null-values: false
        key-prefix: ORD_

server:
  port: "8081"
  servlet:
    context-path: /order-service/v1

queueName: ordersDeletions

